USE [LEI]
GO

/****** Object:  Table [dbo].[Pais]    Script Date: 12/03/2017 15:24:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pais](
	[id] [int] NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
	[Grupo] [nvarchar](50) NOT NULL,
	[Codigo] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


