/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import data.Connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gil
 */
public class ResultadoFinal extends javax.swing.JDialog {
  private String email;
  private String query;
    /**
     * Creates new form ResultadoFinal
     */
    public ResultadoFinal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    public ResultadoFinal(String query,String email) {
    
        initComponents();
        this.email=email;
        this.query=query;
        DefaultTableModel dtm = new DefaultTableModel(0, 0);
        this.comPreferencias.setVisible(false);
        Connection c = null;
        ResultSet rs=null;
       
        
         
      try {
          c = Connect.connect();
          rs = c.createStatement()
                .executeQuery(query);
          ResultSetMetaData rsmd = rs.getMetaData();
          Vector<String> header = new Vector<>();
          int i =0;
          int colunas= rsmd.getColumnCount();
          while(i<colunas) {
                header.add(rsmd.getColumnName(i+1));
                i++;
              
          }
          
    
          Vector<Vector<Object>> data = new Vector<Vector<Object>>();
           while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= colunas; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }
           
           tabela.setModel(new DefaultTableModel(data,header));

          
          
          
          
      } catch (SQLException ex) {
      
          JOptionPane.showMessageDialog(null,
            "Erro a estabelacer conecção",
            "Conecção",
        JOptionPane.ERROR_MESSAGE);
      
      
      }
        
        
        
        
        
        
        
        
        
        
        
      }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semPreferencias = new javax.swing.JButton();
        salto = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        comPreferencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        semPreferencias.setText("Resultado sem as preferencias");
        semPreferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semPreferenciasMouseClicked(evt);
            }
        });
        semPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semPreferenciasActionPerformed(evt);
            }
        });

        salto.setText("Mudar de vista");

        jButton5.setText("voltar Atras");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        comPreferencias.setText("Resultado com Preferencias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semPreferencias)
                                .addGap(81, 81, 81)
                                .addComponent(comPreferencias)
                                .addGap(127, 127, 127)
                                .addComponent(salto))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semPreferencias)
                            .addComponent(comPreferencias))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
      new Medio(email).setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void semPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semPreferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semPreferenciasActionPerformed

    private void semPreferenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semPreferenciasMouseClicked
        // TODO add your handling code here:
        this.comPreferencias.setVisible(true);
    }//GEN-LAST:event_semPreferenciasMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comPreferencias;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salto;
    private javax.swing.JButton semPreferencias;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
